services:
  - type: web
    name: symfony-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:8000 -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
databases:
  - name: ecommerce-db
    plan: free
